apiVersion: v1
kind: Service
metadata:
  name: celflo
  namespace: {{.Values.namespace}}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    revision: {{ .Release.Revision | default 0 | quote }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    image: {{.Values.ImageTag}}
  annotations:
    helm.sh/created: {{ .Release.Time.Seconds | quote }}
spec:
  ports:
    -
      port: 5555
      targetPort: 5555
      protocol: TCP
  selector:
    app: celery-simpl-api
    env: {{.Values.deploymentEnvironment}}
