apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{.Values.namespace}}
data:
  default.conf: |+
    upstream "{{.Values.publicFqdn}}" {
            server unix:/run/gunicorn.sock;
            keepalive 32;
    }

    server {
            listen 80 deferred backlog=10000;

            error_log /dev/stdout info;
            access_log /dev/stdout main;

            proxy_set_header        Host            $host;
            proxy_set_header        X-Real-IP       $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $scheme;
            client_max_body_size    {{.Values.clientMaxBodySize|quote}};
            client_body_buffer_size 128k;
            proxy_connect_timeout   120;
            proxy_send_timeout      120;
            proxy_read_timeout      120;
            proxy_buffers           32 100k;

            proxy_redirect off;

            location / {
            proxy_http_version 1.1;
            #proxy_set_header Connection "";
            proxy_pass http://{{.Values.publicFqdn}};
            }

            location /static {
            alias /code/staticfiles;
            }

            include /etc/nginx/mime.types;

    }
