apiVersion: v1
kind: ConfigMap
metadata:
  name: settings
  namespace: {{.Values.namespace}}
  labels:
    app: simpl-api
    env: {{.Values.deploymentEnvironment}}
    heritage: {{.Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    revision: {{ .Release.Revision | default 0 | quote }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
  annotations:
    helm.sh/created: {{ .Release.Time.Seconds | quote }}
data:
  settings: |+
{{ .Files.Get (printf "settings/%s" .Values.deploymentEnvironment ) | indent 4 }}

