apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simpl-api
  namespace: {{.Values.namespace}}
  labels:
    app: simpl-api
    env: {{.Values.deploymentEnvironment}}
    heritage: {{.Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    revision: {{ .Release.Revision | default 0 | quote }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
  annotations:
    helm.sh/created: {{ .Release.Time.Seconds | quote }}
    revsys.com/pg_db: simpl-{{.Values.deploymentEnvironment}}
    revsys.com/pg_secret_name: simpl-{{.Values.deploymentEnvironment}}
    revsys.com/pg_user_name: simpl
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: simpl-api
      env: {{.Values.deploymentEnvironment}}
  template:
    metadata:
      labels:
        app: simpl-api
        env: {{.Values.deploymentEnvironment}}
        imageTag: {{.Values.ImageTag}}
      annotations:
        chksum/django-config: {{ include (print $.Template.BasePath  "/configmap-django.yaml") . | sha256sum | quote }}
        chksum/nginx-config: {{ include (print $.Template.BasePath  "/configmap-nginx.yaml") . | sha256sum | quote }}
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "migrate",
            "image": "{{ .Values.Image }}:{{ .Values.ImageTag }}",
            "command": ["sh", "-c", "/usr/local/bin/python /code/manage.py migrate || sleep 1000"],
            "env": {{ toJson .Values.Env }},
            "volumeMounts": {{ toJson .Values.DjangoVolumeMounts }}
          },
          {
            "name": "collectstatic",
            "image": "{{ .Values.Image }}:{{ .Values.ImageTag }}",
            "command": ["sh", "-c", "/usr/local/bin/python /code/manage.py collectstatic --noinput || sleep 1000"],
            "env": {{ toJson .Values.Env }},
            "volumeMounts": {{ toJson .Values.DjangoVolumeMounts }}
          }
      ]'
    spec:
      {{ if .Values.tolerations -}}
      tolerations:
{{ toYaml .Values.tolerations | indent 10 }}
      {{- end }}
      volumes:
{{ toYaml .Values.Volumes | indent 8 }}
      imagePullSecrets:
        - name: learninglab.githost.io
      containers:
        -
          name: simpl
          image: {{.Values.Image}}:{{.Values.ImageTag}}
          args:
            - gunicorn
            - -c
            - /code/gunicorn.conf
            - -k
            - gevent
            - config.wsgi
          volumeMounts:
{{ toYaml .Values.DjangoVolumeMounts | indent 12 }}
          env:
{{ toYaml .Values.Env | indent 12 }}
          ports:
            -
              protocol: TCP
              containerPort: 8000
        -
          name: nginx
          image: nginx:{{ .Values.nginxImageTag }}
          volumeMounts:
            -
              name: ngx
              mountPath: /etc/nginx/conf.d
{{ toYaml .Values.NginxVolumeMounts | indent 12 }}
          env:
{{ toYaml .Values.Env | indent 12 }}
          ports:
            - 
              protocol: TCP
              containerPort: 80
