# vim: ft=sls nolist

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simpl-api-{{.Values.deploymentEnvironment}}
  namespace: {{.Values.namespace}}
  labels:
    env: {{.Values.deploymentEnvironment}}
    heritage: {{.Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    revision: {{ .Release.Revision | default 0 | quote }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/proxy-body-size: {{.Values.clientMaxBodySize|quote}}
spec:
  tls:
  - hosts:
    - {{ .Values.publicFqdn }}
    secretName: {{.Values.publicFqdn}}-tls
  rules:
  - 
    host: {{ .Values.publicFqdn }}
    http:
      paths:
      - path: /
        backend:
          serviceName: simpl-api
          servicePort: 80
