apiVersion: v1
kind: Service
metadata:
  name: simpl-dev
  namespace: {{.Values.namespace}}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    revision: {{ .Release.Revision | default 0 | quote }}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    image: {{.Values.ImageTag}}
  annotations:
    helm.sh/created: {{ .Release.Time.Seconds | quote }}
spec:
  ports:
    -
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: simpl-dev
    env: {{.Values.deploymentEnvironment}}
