# vim: ft=sls nolist

Image: learninglab.githost.io:4678/lldev-team/simpl-games-api
ImageTag: v1.4.9
namespace: simpl

nginxImageTag: "1.12.1-alpine"

deploymentEnvironment: dev
clientMaxBodySize: 250m

replicaCount: "1"

publicFqdn: &fqdn simpl.dev.wharton.revsys.com
celeryReplicaCount: 2

Env:
  -
    name: DJANGO_SETTINGS_MODULE
    value: "kube.settings"
  -
    name: DJANGO_FQDN
    value: *fqdn

  # silence django deprecation warnings
  -
    name: PYTHONWARNINGS
    value: ignore
  -
    name: X_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
        apiVersion: v1
  -
    name: X_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
        apiVersion: v1
  -
    name: X_KUBE_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
        apiVersion: v1
  -
    name: X_POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
        apiVersion: v1
  -
    name: DJANGO_DB_NAME
    value: simpl-dev
  -
    name: DJANGO_DB_USER
    value: simpl-dev
  -
    name: DJANGO_DB_HOST
    value: postgres
  -
    name: DJANGO_DB_PORT
    value: "5432"
  -
    name: DJANGO_DB_PASS
    valueFrom:
      secretKeyRef:
        name: simpl-dev
        key: database-password
  -
    name: DJANGO_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: django
        key: secret
  -
    name: DJANGO_DEBUG
    value: ""

# Volumes
Volumes:
  -
    name: run
    emptyDir: {}
  -
    name: staticfiles
    emptyDir: {}
  -
    name: ngx
    configMap:
      name: nginx-config
  -
    name: ngx-server
    configMap:
      name: nginx-server-config
  -
    name: django
    configMap:
      name: settings-simpl
      items:
        -
          key: settings
          path: settings.py
          mode: 0600

DjangoVolumeMounts:
  -
    name: django
    mountPath: /code/kube
  -
    name: staticfiles
    mountPath: /code/staticfiles
  -
    name: run
    mountPath: /run

NginxVolumeMounts:
  -
    name: staticfiles
    mountPath: /code/staticfiles
  -
    name: run
    mountPath: /run
