image: docker:latest

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/lldev-team/simpl-games-api:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/lldev-team/simpl-games-api:latest
  CONTAINER_VERSION_IMAGE: registry.gitlab.com/lldev-team/simpl-tests:$CI_BUILD_TAG

stages:
  - build
  - test
  - release

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  tags:
    - docker
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test:
  tags:
    - docker
  stage: test
  services:
    - postgres:latest
  variables:
    DJANGO_SETTINGS_MODULE: 'config.settings.test'
    SIMPL_GAMES_API_PORT: "8100"
  script:
    - docker run --link $HOSTNAME-postgres:postgres -e "DATABASE_URL=postgres://postgres@postgres/postgres" ${CONTAINER_TEST_IMAGE} /code/tests.sh

release-image:
  tags:
    - docker
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_VERSION_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - tags
  except:
    - branches
