image: docker:latest

services:
  - docker:dind

variables:
  POSTGRES_DB: simpl
  POSTGRES_USER: simpl
  POSTGRES_PASSWORD: ""

  CONTAINER_TEST_IMAGE: registry.gitlab.com/lldev-team/simpl-games-api:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/lldev-team/simpl-games-api:latest

stages:
  - build
  - test
  - release

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  tags:
    - dind
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test:
  tags:
    - dind
  stage: test
  script:
    - apk update && apk add py-pip
    - pip install docker-compose
    - docker-compose run simpl-games-api /code/tests.sh

release-image:
  tags:
    - dind
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - develop
