version: '3'

services:
  db:
    image: postgres:9.6
    networks:
      - simpl
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  api:
    build:
      context: .
    volumes:
      - .:/code
    ports:
      - "8100:8000"
    command: ["/bin/bash", "/code/start.sh"]
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DJANGO_DEBUG=1
      - GUNICORN_BIND=0.0.0.0:8000
      - DEBUG=True
    depends_on:
      - db
    stop_signal: SIGTERM
    networks:
      - simpl

networks:
  simpl:
    driver: bridge

volumes:
  postgres_data:
