version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build:
      context: .
    volumes:
      - .:/code
    ports:
      - "8100:8000"
    command: ["/bin/bash", "/code/start.sh"]
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - GUNICORN_BIND=0.0.0.0:8000
      - DEBUG=True
    depends_on:
      - db
      - redis
      - memcached
    stop_signal: SIGTERM
  memcached:
    image: "memcached:1.6.5-alpine"
    stop_signal: SIGKILL
  redis:
    image: "redis:alpine"
    stop_signal: SIGKILL
  celery:
    build: .
    command: celery -A config worker -l debug
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    stop_signal: SIGTERM


volumes:
  postgres_data:
