version: '3'

services:
  db:
    image: postgres:10.15-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - simpl
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  api:
    build:
      context: .
    volumes:
      - .:/code
    ports:
      - "8100:8000"
    command: ["/bin/bash", "/code/start.sh"]
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DJANGO_DEBUG=1
      - GUNICORN_BIND=0.0.0.0:8000
    depends_on:
      - db
      - redis
      - memcached
    stop_signal: SIGTERM
    networks:
      - simpl

  memcached:
    image: "memcached:1.6.5-alpine"
    stop_signal: SIGKILL
    networks:
      - simpl

  redis:
    image: "redis:alpine"
    stop_signal: SIGKILL
    networks:
      - simpl

  celery:
    build: .
    command: celery -A config worker -l debug
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DJANGO_DEBUG=1
      - DEBUG=True
    stop_signal: SIGTERM
    networks:
      - simpl

networks:
  simpl:
    driver: bridge

volumes:
  postgres_data:
