apiVersion: v1
kind: Endpoints
metadata:
  name: postgres
  namespace: {{.Values.namespace}}
subsets:
  -
    addresses:
{{- if eq .Values.deploymentEnvironment "dev" }}
      - ip: 10.71.63.250
{{- else if eq .Values.deploymentEnvironment "prod" }}
      - ip: 172.31.28.2
{{- else if eq .Values.deploymentEnvironment "playground" }}
      - ip: 172.31.28.2
{{- end }}
    ports:
      -
        port: 5432
        name: postgres

